name: notificaciones
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  video_player: ^2.9.5
  flutter_webrtc: ^0.13.1+hotfix.1
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  logger: ^2.5.0
  intl: ^0.19.0
  flutter_vlc_player: ^7.4.3
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  app_links: ^6.4.0
  better_player_plus: ^1.0.8
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/