// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1As7_ufAC9URZiuII8guJ2FjRR9LGpU',
    appId: '1:201347486772:web:fb28ef9eb61fbadc61a661',
    messagingSenderId: '201347486772',
    projectId: 'notificacionestest-7c1c8',
    authDomain: 'notificacionestest-7c1c8.firebaseapp.com',
    storageBucket: 'notificacionestest-7c1c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNADF4ThdsuDYTBndM99ys_RRKh0KncU',
    appId: '1:201347486772:android:f65443589cbc3f5d61a661',
    messagingSenderId: '201347486772',
    projectId: 'notificacionestest-7c1c8',
    storageBucket: 'notificacionestest-7c1c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QGJuyWP_cPq1-kTYzdDubxMIHCCa8Uc',
    appId: '1:201347486772:ios:9f79093742f8bd1161a661',
    messagingSenderId: '201347486772',
    projectId: 'notificacionestest-7c1c8',
    storageBucket: 'notificacionestest-7c1c8.firebasestorage.app',
    iosBundleId: 'com.example.notificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QGJuyWP_cPq1-kTYzdDubxMIHCCa8Uc',
    appId: '1:201347486772:ios:9f79093742f8bd1161a661',
    messagingSenderId: '201347486772',
    projectId: 'notificacionestest-7c1c8',
    storageBucket: 'notificacionestest-7c1c8.firebasestorage.app',
    iosBundleId: 'com.example.notificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi1As7_ufAC9URZiuII8guJ2FjRR9LGpU',
    appId: '1:201347486772:web:fdc4795187c3038261a661',
    messagingSenderId: '201347486772',
    projectId: 'notificacionestest-7c1c8',
    authDomain: 'notificacionestest-7c1c8.firebaseapp.com',
    storageBucket: 'notificacionestest-7c1c8.firebasestorage.app',
  );
}
